language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "node"
  - 1
  - 2
  - 3
  - 4
  - 5
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
