language: node_js
sudo: false
node_js:
  - "4.0.0"
  - "4.1.2"
  - "4.2.3"
  - "5.0.0"
  - "5.1.0"
  - "5.1.1"
  - "5.2.0"
  - 5
  - 6
  - 7
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
